name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          pip install pillow
      - name: Compile sources
        run: python -m compileall pipeline_core video_processor.py run_pipeline.py
      - name: Run tests
        run: |
          pip install pytest
          pytest -q
      - name: No persistent cache check
        run: |
          if (Test-Path cache) { throw "cache/ must not exist in CI" }
          if (Test-Path broll_cache) { throw "broll_cache/ must not exist in CI" }
      - name: Smoke JSONL path exists (doc only)
        run: echo "JSONL is generated during full runs; unit tests cover logger."
